# Generated by Django 2.2 on 2022-01-29 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
