# Generated by Django 2.2 on 2022-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220129_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='prace',
            field=models.FloatField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='todo',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров0'),
        ),
    ]
