# Generated by Django 2.2 on 2022-01-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220129_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='Tasks',
        ),
    ]
